config/routes.rb
SampleApp::Application.routes.draw do

  root 'customers#index'
  
  resources :customers
  
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :customer
	belongs_to :address_type

	validates_presence_of :primary_address, :city, :state
end

app/models/address_type.rb
class AddressType < ActiveRecord::Base
	has_many :addresses, :dependent => :destroy
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :addresses, :dependent => :destroy
	accepts_nested_attributes_for :addresses

	validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # RENJANA
  # version 1
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def index
		@customers = Customer.all 
	end

	def show
		@customer = Customer.find(params[:id]) 
	end

	def new
		@customer = Customer.new
		2.times { @customer.addresses.build }
		# @address = @customer.addresses.new
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def create
		@customer = Customer.new(customer_params)
		if @customer.save
			flash[:notice] = "Customer created succesfully"
			redirect_to customers_path
		else
			flash[:error] = "Error while creating customer"
			render :new
		end
	end

	def update
		@customer = Customer.find(params[:id])
		if @customer.update_attributes(customer_params)
			flash[:notice] = "Customer updated succesfully"
			redirect_to customers_path
		else
			flash[:error] = "Error while updating customer"
			render :edit
		end
	end

	def destroy
		@customer = Customer.find(params[:id])
		if @customer.destroy
			flash[:notice] = "Customer deleted succesfully"
		else
			flash[:error] = "Error while deleting customer"
		end
		redirect_to customers_path
	end

	private

	def customer_params
		params.require(:customer).permit(:first_name, :last_name, addresses_attributes: [:id, :primary_address, :city, :state, :address_type_id] )
	end
	
end
	

app/helpers/application_helper.rb
module ApplicationHelper

	def validation_errors(message)
		if message.class.to_s == "Array"
			message = message.join(", ")
		end
		return !message.to_s.blank? ? message.to_s: ""
	end
	
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f|%>
<table>
  <tr>
    <td>
      <%= f.label :first_name %>
    </td>
    <td>
      <%=f.text_field :first_name%>
      <div style='color: red;'><%= validation_errors @customer.errors['first_name'] %></div>
    </td>
  </tr>

  <tr>
    <td>
      <%= f.label :last_name %>
    </td>
    <td>
      <%=f.text_field :last_name%>
      <div style='color: red;'><%= validation_errors @customer.errors['last_name'] %></div>
    </td>
  </tr>

  <%= f.fields_for :addresses do |address|%>

  <tr>
    <td>
      <%= address.label :primary_address %>
    </td>
    <td>
      <%=address.text_field :primary_address%>
      <div style='color: red;'><%= validation_errors @customer.errors['addresses.primary_address'] %></div>
    </td>
  </tr>

  <tr>
    <td>
      <%= address.label :city %>
    </td>
    <td>
      <%=address.text_field :city%>
      <div style='color: red;'><%= validation_errors @customer.errors['addresses.city'] %></div>
    </td>
  </tr>

  <tr>
    <td>
      <%= address.label :state %>
    </td>
    <td>
      <%=address.text_field :state%>
      <div style='color: red;'><%= validation_errors @customer.errors['addresses.state'] %></
      </td>
    </tr>

    <tr>
      <td>
        <%= address.label :address_type_id %>
      </td>
      <td>
        <%=address.select :address_type_id, options_for_select(AddressType.all.collect{|x|[x.add_type,x.id]})%>
      </td>
    </tr>

    <% end %>

  </table>
  <%=f.submit "Save"%>
  <% end %>


  <%= link_to "Back", customers_path%>

app/views/customers/edit.html.erb
<h1> Edit customer </h1>
<%= render 'form' %>

app/views/customers/index.html.erb
<h1>Listing Customers</h1>
<div style="float:right"><%= link_to "New customer", new_customer_path %></div>
<table border="1" style="width:100%">

  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Primary Address</th>
      <th>City</th>
      <th>State</th>
      <th>Address Type</th>
      <th colspan="3"> Actions </th>
    </tr>
  </thead>

  <tbody>
    <% unless @customers.empty? %>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.first_name %></td>
      <td><%= customer.last_name %></td>
      <td><%= customer.addresses.first.primary_address %></td>
      <td><%= customer.addresses.first.city%></td>
      <td><%= customer.addresses.first.state%></td>
      <td><%= customer.addresses.first.address_type.add_type%></td>
      <td><%= link_to "Edit" , edit_customer_path(customer) %></td>
      <td><%= link_to "Show" , customer_path(customer) %></td>
      <td><%= link_to "Delete" , customer_path(customer), method: :delete %></td>
    </tr>
    <% end %>
    <% else %>
    <tr>
      <td colspan="6" style="text-align:center">No customers found</td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<h1> Create new customer </h1>
<%= render 'form' %>

app/views/customers/show.html.erb
<h2> Customer show page </h2>

<ul> 
  <li> <%= @customer.first_name %> </li>
  <li> <%= @customer.last_name %> </li>
  <li> 
    <h3> Customer address </h3>
    <ul>
      <li><%= @customer.addresses.first.primary_address %></li>
      <li><%= @customer.addresses.first.city%></li>
      <li><%= @customer.addresses.first.state%></li>
      <li><%= @customer.addresses.first.address_type.add_type%></li>
    </ul>
  </li>
</ul>
<%= link_to "Home", customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>